---
title: "Untitled"
output: ioslides_presentation
date: "2023-05-24"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```



```{r all_plots, echo=FALSE, message=FALSE,results = "asis"}
for (i in 1:3) {
  cat("## Slide with Plot  \n")
  cat("<div style=\"float: left; width: 75%;\">")
  # Use the output_plot function to create four plots, and then arrange in a grid.
  # Input arguments are type, title, quantity and y-axis label
  g_co2perha <- output_plot(i, "Absolute emissions", "t CO2-e per ha", "t CO"[2]~"-e / ha", "#23A845")
  g_co2perkg <- output_plot(i, "Emission intensity", "kg CO2-e per kg output", "kg CO"[2]~"-e / kg output", "#23A845")
  g_Nsurplus <- output_plot(i, "Nitrogen balance", "Nitrogen surplus (kg)", "kg N surplus / ha", "#80BA27")
  g_NUE <- output_plot(i, "Nitrogen use efficiency", "Nitrogen use efficiency (%)", "NUE (%)", "#80BA27")
  if(i==9){
    farmtype_title <- "All farm types"
  } else{
    farmtype_title <- fbs_type_words[i]
  }
  g_grid <- grid.arrange(g_co2perha, g_co2perkg, g_Nsurplus, g_NUE,
                         top=textGrob(farmtype_title,gp=gpar(fontsize=20,font=2),x=0,hjust=0))
  cat("</div>")
  cat("<div style=\"float: right; width: 25%;\">")
  # ```{r commentaries, results="asis"}
  ##Individual farmtype commentaries
  #Cereal
  if(i==1){cat('Cereals, such as barley and wheat are lorum ipsum...')}
  #General cropping
  if(i==2){cat('General cropping commentary goes here...')}
  #Dairy
  if(i==3){cat('')}
  #Mixed
  if(i==8){cat('')}
  #All farms
  if(i==9){cat('')}
  #All LFA livestock farms
  if(i==10){cat('')}
  cat('</div>')
}
```
